### ISSUE TITLE
Wiki全体(このリポジトリの親ディレクトリに相当)をGitで管理する

### ISSUE THREAD

**Issue by fumieval** [haskell-jp/haskell-jp-wiki#1]
## 目的

* CSSなどの静的ファイルを変更可能にするため、Wiki全体をカバーするリポジトリを作る。
* Circle CIにより、@igrepさんが管理しているHerokuのappにデプロイする。

## 疑問

* 「gititの仕様上、wikiを編集するたびに大本のリポジトリーにもコミットされるため、そのままだと編集するたびにデプロイまでされてしまう」
  * 全体用のリポジトリでは`wikidata`を無視する？

## 参考になりそうなもの
* CircleCI 2.0 でGithubにpushした時herokuにデプロイする
 https://qiita.com/sizukutamago/items/76d3ca5d37b1b2bbcd1b

**Comment by igrep** [comment]
もうHerokuでホストしているわけでもないし、現在編集できるわけでもないので無効なissueと判断し、closeします。
