### ISSUE TITLE
日本語が混ざったコミットメッセージを与えるとエラーを返すことがある

### ISSUE THREAD

**Issue by igrep** [haskell-jp/haskell-jp-wiki#14]
https://github.com/haskell-jp/haskell-jp-wiki/pull/12 の前からか後からかはわかりませんが、今日たまたま編集していたら確認した。
https://github.com/jgm/gitit/issues/393 と同じ現象と思われる。
多分Docker imageのロケールの設定を正しく行えば解決すると思う。

**Comment by igrep** [comment]
データ構造列伝にもアクセスできなくなってしまっているらしい。
同様に `invalid argument (invalid character)` というエラーが出ていることからして、同じ原因と思われる。

**Comment by Profpatsch** [comment]
ありがとうごさいます。

This was very helpful to fix https://github.com/jgm/gitit/issues/393.
